### ISSUE TITLE
KO for parsing files missing

### ISSUE THREAD

**Issue by wanboqi** [nashanghenzan/KEGG-KO-htext-file-parser#1]
@nashanghenzan Hello, I found that after running your script, there will be some missing KO in kegg_htext file, such as K00023 missing such cases, I also refer to the python text of other people on the network, but there will be this situation, I do not understand why this happens? Logically speaking, even if the new KO is added after kegg, the format is the same, hope to answer, thank you!!

**Comment by nashanghenzan** [comment]
Maybe you should download the newest json file and try my script again, I can find K00023 in my result file.
![image](https://github.com/nashanghenzan/KEGG-KO-htext-file-parser/assets/116560726/819aca39-e757-4b84-81e3-622c2c41ae51)

**Comment by wanboqi** [comment]
@nashanghenzan Thank you for your reply and I'm sorry for causing you misunderstanding. This KO is just an example I gave. If I use real data, I have downloaded the latest ko00001.json file and found that some KO is missing, but there is indeed some KO in the ko00001.json file. For example, K00092 is definitely not in the PATHWAY.tsv file.

**Comment by nashanghenzan** [comment]
> @nashanghenzan Thank you for your reply and I'm sorry for causing you misunderstanding. This KO is just an example I gave. If I use real data, I have downloaded the latest ko00001.json file and found that some KO is missing, but there is indeed some KO in the ko00001.json file. For example, K00092 is definitely not in the PATHWAY.tsv file.
K00092 can't be found in newest json file.
![image](https://github.com/nashanghenzan/KEGG-KO-htext-file-parser/assets/116560726/abc202b0-38b8-450a-9e74-bb490cae3bfa)

**Comment by wanboqi** [comment]
@nashanghenzan Thank you for your reply. I may know the reason. When I made kegg comments, I used the database of 2019, while the latest ko00001.json is from 2024. Some KO may have been deprecated, so I cannot find it in the latest file. Thank you again for your reply!!
